### ISSUE TITLE
Plugin crushing Homebridge crypto.js:181

### ISSUE THREAD

**Issue by iandronowicz** [nitaybz/homebridge-broadlink-s1c#7]
First of all: thank you for your work! It's great, really.

Now to the issue: the plugin is randomly crashing Homebridge:

[11/27/2017, 6:46:36 PM] [Broadlink RM] Aire Acondicionado Living getCurrentHeatingCoolingState: 0
[11/27/2017, 6:53:41 PM] [S1C] Door Sensor state is - Open
[11/27/2017, 6:53:50 PM] [S1C] Door Sensor state is - Close
crypto.js:181
  var ret = this._handle.final();
                         ^

Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Decipheriv.final (crypto.js:181:26)
    at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-s1c/node_modules/broadlinkjs-s1c/index.js:235:27)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:619:8)

**Comment by nitaybz** [comment]
Sorry for the delay... I finally found a way to fix it... working on that

**Comment by nitaybz** [comment]
please check the latest version (v3)

**Comment by nitaybz** [comment]
did you check the latest version? I want to close ticket because I'm not experiencing this issue anymore...

**Comment by nitaybz** [comment]
closing
